# basics
alias l='ls'
alias ll='ls -l'
alias la='ls -la'
alias b='cd ..'
alias bb='cd ../..'
alias bbb='cd ../../..'
alias e='emacs'
alias o='open'
alias be='bundle exec'

## hub->git
alias git='hub'

## git
alias ga='git add'
alias gco='git commit'
alias gcoa='git commit -a'
alias gam='git commit --amend -C HEAD'
# alias gc='git checkout'
alias gb='git branch'
alias gcb='git checkout -b'
alias gpus='git push -u'
alias gpush='gpus'
alias gpul='git pull'
alias gs='git status'
alias gl='git log'
alias gm='git merge'
alias gr='git rebase'
alias gd='git diff'
alias gdc='git diff --cached'
alias gss='git stash save -u'
alias gsp='git stash pop'
alias gsa='git stash apply'
alias gsl='git stash list'
alias gbr='git browse'
alias gcl='git clone'
alias gcom='git compare'
alias gg='git grep -i -n'
alias gris='git rebase -i --autosquash'
